### PR TITLE
Solution for Issue #152: Custom template option doesn't work 

### PR DESCRIPTION
**Pull request by shatran**
Iv'e moved this.template assignment to occur before calling this.setup() in the constructor.
that way when this.setup() is called, this.template() is the correct template - the default one or the customised one.

### CODE REVIEW

**Comment by burnnat** [comment]
:+1:

One year later, any plans for this to be merged? Without it, custom templates don't work...

**Comment by shatran** [comment]
@danielfarrell any chance it will be merged?

**Comment by danielfarrell** [comment]
@shatran I haven't been maintaining the project for some time.  @thephw has been doing that.

**Comment by shatran** [comment]
@thephw any chance it will be merged?

**Comment by premkumar-gg** [comment]
Finally :)

Good job

**Pull request merged**
